### ISSUE TITLE
Update has not been published on flathub.

### ISSUE THREAD

**Issue by zaclegarssure** [flathub/com.whitemagicsoftware.kmcaster#2]
If you look at the version on flathub (with flatpak remote-info or just at this [link](https://flathub.org/apps/details/com.whitemagicsoftware.kmcaster) you will see that it is still the one from March 2021, while the manifest clearly got updated in the meantime and the build was apparently successful. I have no idea why it would be the case, but maybe someone can try to relaunch the build.

**Comment by yajo** [comment]
I've no idea what's happening. I rebuilt it in https://flathub.org/builds/#/builders/32/builds/92695 and published that, but I still see the old version in https://flathub.org/apps/details/com.whitemagicsoftware.kmcaster. 😕

**Comment by zaclegarssure** [comment]
It now shows May 2022 on the flathub page, I think this is solved, thanks for your time.
I will close this for now, but since this is a really odd problem maybe I should report it on the flahub buildbot github.
