### ISSUE TITLE
Mark kmcaster as EOL

### ISSUE THREAD

**Issue by yakushabb** [flathub/com.whitemagicsoftware.kmcaster#4]
The source code repository and developer account related to kmcaster seem to have been deleted.

@bbhtt Is it possible to mark the application as EOL?

https://github.com/DaveJarvis/kmcaster/

**Comment by bbhtt** [comment]
https://github.com/flathub/com.whitemagicsoftware.kmcaster/releases/download/1.1.0/kmcaster.jar replace the url with this.

**Comment by yajo** [comment]
Woah it vanished! Isnt around an archive.org or similar alternative? No github.com forks?

**Comment by bbhtt** [comment]
I uploaded the last tarball as a release, you can use that to EOL it.
